"""VERL backend — production, multi-GPU reinforcement learning.

The mlx/torch GRPO paths run on a single process; this one drives
[VERL](https://github.com/volcengine/verl) (ByteDance's RL engine — vLLM
rollouts, FSDP/Megatron training, Ray orchestration) for `method="grpo"` at
cluster scale. The agent boundary is unchanged: you still `capture()` traffic
and pass `reward_fns`; this backend translates ShadowLM's `TrainConfig` into a
VERL run, launches it, and streams its progress back through `Callbacks`.

It's the heavy, opt-in path: `pip install shadowlm[verl]` and a box with
NVIDIA GPUs. Pick it with `backend="verl"`.

What's covered here and unit-tested: the Backend contract, the
`TrainConfig → VERL override` mapping, the dataset → parquet export, and the
launch/stream/readback flow. What needs a GPU box to validate: an actual VERL
run. Logs say so rather than implying otherwise.
"""

from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path

from ..data import Dataset
from ..training import TrainConfig, resolve_total_steps
from .base import Backend, Callbacks, FinetuneResult


def _build_overrides(model: str, config: TrainConfig, *, train_parquet: str,
                     val_parquet: str | None, output_dir: str, n_rows: int,
                     reward_path: str | None) -> list[str]:
    """Map a ShadowLM TrainConfig to VERL `main_ppo` Hydra overrides (GRPO recipe).

    Pure and unit-testable — the one place that knows VERL's config surface, so
    it's the one place to adjust if your VERL version renames a key.
    """
    total = resolve_total_steps(config, n_rows)
    group = config.grpo_group_size or 8
    ov = [
        "algorithm.adv_estimator=grpo",
        f"data.train_files=[{train_parquet}]",
        f"data.val_files=[{val_parquet or train_parquet}]",
        f"data.max_response_length={config.grpo_max_completion_length or 512}",
        f"data.max_prompt_length={config.max_seq_length}",
        f"actor_rollout_ref.model.path={model}",
        f"actor_rollout_ref.actor.optim.lr={config.learning_rate:g}",
        f"actor_rollout_ref.actor.kl_loss_coef={config.beta}",
        f"actor_rollout_ref.rollout.n={group}",
        "actor_rollout_ref.rollout.name=vllm",
        f"trainer.total_training_steps={total}",
        f"trainer.default_local_dir={output_dir}",
        "trainer.logger=[console]",
    ]
    if reward_path:
        ov.append(f"custom_reward_function.path={reward_path}")
        ov.append("custom_reward_function.name=compute_score")
    # escape hatch: append any raw Hydra overrides (space-separated) so you can
    # tune VERL — GPU memory, batch sizes, tensor parallel — without code changes.
    # e.g. SHADOWLM_VERL_OVERRIDES="actor_rollout_ref.rollout.gpu_memory_utilization=0.4"
    ov.extend(os.environ.get("SHADOWLM_VERL_OVERRIDES", "").split())
    return ov


def _reward_shim(reward_fns: list) -> str:
    """Source for a VERL `compute_score(...)` that calls ShadowLM reward_fns.

    VERL imports the reward by file path; ShadowLM's reward_fns are Python
    callables, so we reference them by import path. Lambdas and functions defined
    in `__main__` can't be imported into VERL's workers — those raise with a clear
    message instead of failing deep inside Ray.
    """
    refs = []
    for fn in reward_fns:
        mod = getattr(fn, "__module__", None)
        qn = getattr(fn, "__qualname__", None)
        if not mod or mod == "__main__" or not qn or "<" in qn:
            raise ValueError(
                f"VERL imports reward functions by path, so {qn or fn!r} must be a "
                "named function in an importable module (not a lambda or one defined "
                "in __main__). Move it into a module and pass that function."
            )
        refs.append((mod, qn))
    imports = "\n".join(f"from {m} import {q.split('.')[0]} as _r{i}"
                        for i, (m, q) in enumerate(refs))
    calls = " + ".join(f"_r{i}(prompts=[extra_info.get('prompt','')], "
                       f"completions=[solution_str], answer=ground_truth)[0]"
                       for i in range(len(refs)))
    return (
        "# generated by shadowlm — adapts ShadowLM reward_fns to VERL's contract\n"
        f"{imports}\n\n"
        "def compute_score(data_source, solution_str, ground_truth, extra_info=None):\n"
        "    extra_info = extra_info or {}\n"
        f"    return float({calls})\n"
    )


def _to_parquet(dataset: Dataset, path: str) -> int:
    """Write rows in VERL's expected schema (prompt as chat + ground_truth).

    Uses pyarrow directly (a core datasets/verl dependency) rather than pandas —
    one less heavy import, and it sidesteps the numpy/pandas ABI clashes the
    verl+vllm install tends to leave behind.
    """
    import pyarrow as pa  # noqa: PLC0415
    import pyarrow.parquet as pq  # noqa: PLC0415

    rows = []
    for r in dataset.rows:
        prompt = r.get("prompt") or r.get("instruction") or r.get("question") or ""
        answer = r.get("answer") or r.get("output") or r.get("response") or ""
        rows.append({
            "data_source": "shadowlm",
            "prompt": [{"role": "user", "content": prompt}],
            "ability": "shadowlm",
            "reward_model": {"style": "rule", "ground_truth": answer},
            "extra_info": {"prompt": prompt, "answer": answer},
        })
    pq.write_table(pa.Table.from_pylist(rows), path)
    return len(rows)


class VerlBackend(Backend):
    name = "verl"

    @classmethod
    def is_available(cls) -> bool:
        return importlib.util.find_spec("verl") is not None

    def load(self, name: str, *, load_in_4bit: bool = False, max_seq_length: int = 2048,
             adapter: str | None = None, **kwargs) -> None:
        # VERL loads the model inside its own workers; we just remember which one.
        self.model_name = name
        self._adapter = adapter

    def finetune(self, dataset: Dataset, config: TrainConfig, callbacks: Callbacks,
                 output_dir: str, eval_dataset: Dataset | None = None,
                 reward_fns: list | None = None) -> FinetuneResult:
        if config.method != "grpo":
            raise ValueError(
                f"the verl backend trains method='grpo' only (got {config.method!r}); "
                "use backend='torch'/'mlx' for SFT/DPO/LoRA, or capture→judge→grpo here."
            )
        if not reward_fns:
            raise ValueError(
                "verl GRPO needs reward_fns=[...] — it generates rollouts and scores "
                "them online (it can't learn from pre-collected trajectories)."
            )
        if not self.is_available():
            raise RuntimeError("verl backend needs `pip install shadowlm[verl]` (verl + vllm + ray).")

        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        train_pq = str(out / "train.parquet")
        n = _to_parquet(dataset, train_pq)
        val_pq = None
        if eval_dataset is not None and len(eval_dataset):
            val_pq = str(out / "val.parquet")
            _to_parquet(eval_dataset, val_pq)
        reward_path = str(out / "reward.py")
        Path(reward_path).write_text(_reward_shim(reward_fns))

        overrides = _build_overrides(
            self.model_name or "", config, train_parquet=train_pq, val_parquet=val_pq,
            output_dir=str(out), n_rows=n, reward_path=reward_path)
        cmd = [sys.executable, "-m", "verl.trainer.main_ppo", *overrides]
        callbacks.log(f"[verl] launching {self.model_name} · grpo · {n} prompts "
                      f"· group {config.grpo_group_size or 8} · {len(reward_fns)} reward fn(s)")
        callbacks.log(f"[verl] {' '.join(cmd)}")

        # stream VERL's stdout into the callback log; surface step lines if present
        last_loss = None
        proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                text=True, bufsize=1)
        assert proc.stdout is not None
        for line in proc.stdout:
            line = line.rstrip()
            if line:
                callbacks.log(f"[verl] {line}")
            if callbacks.stopped():
                proc.terminate()
                break
        code = proc.wait()
        if code != 0:
            raise RuntimeError(f"verl run exited with code {code} — see the log above")

        # VERL writes checkpoints under trainer.default_local_dir
        ckpts = sorted(out.glob("global_step_*"))
        checkpoint = str(ckpts[-1]) if ckpts else str(out)
        callbacks.log(f"[verl] done · checkpoint {checkpoint}")
        return FinetuneResult(checkpoint=checkpoint, final_loss=last_loss)

    def generate(self, prompt: str, *, max_new_tokens: int, temperature: float,
                 top_p: float, **kwargs) -> str:
        raise NotImplementedError(
            "the verl backend trains only — load the trained checkpoint for "
            "inference with backend='torch': slm.load(path, backend='torch')."
        )
